runtime: python27
entrypoint: uwsgi --http-socket :8080 --wsgi-file main.py --callable app --master --processes 1 --threads 2
api_version: 1
threadsafe: true

handlers:
  - url: /static
    static_dir: static
    application_readable: true

  - url: /.*
    script: main.app

libraries:
  - name: ssl
    version: latest

env_variables:
  GAE_USE_SOCKETS_HTTPLIB: "anyvalue"
