runtime: python27
entrypoint: uwsgi --http-socket :8080 --wsgi-file main.py --callable app --master --processes 1 --threads 2
api_version: 1
threadsafe: true

handlers:
  - url: /static
    static_dir: static
    application_readable: true
    http_headers:
      Access-Control-Allow-Origin: "*"

  - url: /input-table-teams-data
    static_dir: static
    http_headers:
      Access-Control-Allow-Origin: "*"

  - url: /get_game
    static_dir: static
    http_headers:
      Access-Control-Allow-Origin: "*"

  - url: /substandard-fixtures-content.html
    static_dir: static
    http_headers:
      Access-Control-Allow-Origin: "*"

  - url: /.*
    script: main.app

libraries:
  - name: ssl
    version: latest

env_variables:
  GAE_USE_SOCKETS_HTTPLIB: "anyvalue"
