runtime: python39

handlers:
  - url: /static
    static_dir: static
    http_headers:
      Access-Control-Allow-Origin: "*"

  - url: /input-table-teams-data
    static_dir: static
    http_headers:
      Access-Control-Allow-Origin: "*"

  - url: /results
    static_dir: static
    http_headers:
      Access-Control-Allow-Origin: "*"

  - url: /fixtures
    static_dir: static
    http_headers:
      Access-Control-Allow-Origin: "*"

  - url: /this_weekend_fixtures
    static_dir: static
    http_headers:
      Access-Control-Allow-Origin: "*"

  - url: /last_weekend_results
    static_dir: static
    http_headers:
      Access-Control-Allow-Origin: "*"

  - url: /.*
    script: auto
